server.port = 3010

# Database Connection
spring.autoconfigure.exclude = org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

#Local Server
#spring.datasource.url=jdbc:mysql://localhost:3306/indentmaster
#spring.datasource.username=root
#spring.datasource.password=xxxx

spring.datasource.primary.jdbcUrl=jdbc:mysql://localhost:3306/indentmaster
spring.datasource.primary.username=root
spring.datasource.primary.password=xxxx
spring.datasource.primary.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.secondary.jdbcUrl=jdbc:mysql://localhost:3306/iboard
spring.datasource.secondary.username=root
spring.datasource.secondary.password=xxxxx
spring.datasource.secondary.driver-class-name=com.mysql.cj.jdbc.Driver

#service.b.base-url=http://localhost:8082
#service.b.process-endpoint=/service-b/process/

spring.servlet.multipart.enabled=true

# Threshold after which files are written to disk.
spring.servlet.multipart.file-size-threshold=10KB

# Max file size.
spring.servlet.multipart.max-file-size=16MB

# Max Request Size
spring.servlet.multipart.max-request-size=16MB

#Mail Service
spring.mail.host=smtp.office365.com
spring.mail.port=587
#(above can be used for gmail)
spring.mail.username=xxxxx
spring.mail.password=xxxxx
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000